/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-06-13 06:33:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;

public final class gide_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/KimSoYoung/tofit/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/tofit/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1683813509779L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/footer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/gide.css\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.6.3.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/gide.js\"></script>\r\n");
      out.write("<title>TOFIT</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<div id=\"content\">\r\n");
      out.write("		<div id=\"content_tit\">\r\n");
      out.write("			<p class=\"headtit\">\r\n");
      out.write("				<span>투핏은</span> <span>이렇게 진행됩니다. 🙌🏻</span>\r\n");
      out.write("			</p>\r\n");
      out.write("			<p class=\"s_tit\">\r\n");
      out.write("				<span>온라인 맞춤 피티 투핏,</span> <span>지금 시작해보세요!</span>\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"introduce\">\r\n");
      out.write("			<div class=\"col1\">\r\n");
      out.write("				<div class=\"col1_inner\">\r\n");
      out.write("					<p class=\"col1_tit\">\r\n");
      out.write("						<span>투핏이 선정한 운동 전문가가</span> <span>당신의 코치가 됩니다.</span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p class=\"col1_tit2\">\r\n");
      out.write("						함께 하고픈 코치, <br> 하고 싶었던 운동 분야, <br> 원하는 프로그램을 선택하세요. <br>\r\n");
      out.write("					</p>\r\n");
      out.write("					<div class=\"tip\">\r\n");
      out.write("						<b>Tip</b>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"introduce_inner\">\r\n");
      out.write("				<div class=\"introd_pic1\">\r\n");
      out.write("					<img class=\"intr_pic1\"\r\n");
      out.write("						src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/gide1.png\" alt=\"소개사진\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"introduce\">\r\n");
      out.write("			<div class=\"col1\">\r\n");
      out.write("				<div class=\"col1_inner col2\">\r\n");
      out.write("					<p class=\"col1_tit\">\r\n");
      out.write("						<span>진단 설문에 답하고</span> <span>지금 상태에 꼭맞는 커리큘럼을</span> <span>코치가\r\n");
      out.write("							직접 재공해 드립니다.</span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p class=\"col1_tit2\">\r\n");
      out.write("						진단 설문은 코칭룸에서 답할 수 있습니다. <br> 설문 제출 후 맞춤 커리큘럼을 기다려 주세요. 신청 후\r\n");
      out.write("						바로 <br> 진행해 주세요. <br>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"introduce_inner\">\r\n");
      out.write("				<div class=\"introd_pic2\">\r\n");
      out.write("					<img class=\"intr_pic2\"\r\n");
      out.write("						src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/gide3.png\" alt=\"소개사진\">\r\n");
      out.write("					<img class=\"intr_pic3\"\r\n");
      out.write("						src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/gide2.png\" alt=\"소개사진\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"introduce\">\r\n");
      out.write("				<div class=\"col1\">\r\n");
      out.write("					<div class=\"col1_inner col2\">\r\n");
      out.write("						<p class=\"col1_tit\">\r\n");
      out.write("							<span>코치와 1:1로</span> <span>직접 상담하세요.</span>\r\n");
      out.write("						</p>\r\n");
      out.write("						<p class=\"col1_tit2\">\r\n");
      out.write("							운동하며 궁금했던 점, <br> 코치에게 전하고 싶은 말 등등 <br> 코치와의 상담은 언제든 열려\r\n");
      out.write("							있습니다. <br>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"introduce_inner\">\r\n");
      out.write("					<div class=\"introd_pic2\">\r\n");
      out.write("						<img class=\"intr_pic3\"\r\n");
      out.write("							src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/gide5.png\" alt=\"소개사진\">\r\n");
      out.write("						<img class=\"intr_pic2\"\r\n");
      out.write("							src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/gide6.png\" alt=\"소개사진\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"gide_title\">\r\n");
      out.write("				<span class=\"gtit1\">내 몸에 잘 맞는 운동</span> <span class=\"gtit1\">TOFIT</span>\r\n");
      out.write("				<p>\r\n");
      out.write("					<span>온라인 맞춤 피티 키핏,</span> <span>지금 시작해보세요!</span>\r\n");
      out.write("				</p>\r\n");
      out.write("				<br> <a href=\"./index.html\">키핏 프로그램 만나기 👍🏻</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mainFQA\">\r\n");
      out.write("			<div class=\"fqa_contant\">\r\n");
      out.write("				<h4>자주 묻는 질문 (FQA)</h4>\r\n");
      out.write("				<ul class=\"mainFQA\">\r\n");
      out.write("					<li><a class=\"selected\">프로그램을 결제했는데 운동은 어떻게 시작하나요?</a>\r\n");
      out.write("						<div class=\"answe\">코칭룸에서 진단 설문에 답해 주세요. 지금 상태를 진단하여, 꼭 맞는\r\n");
      out.write("							커리큘럼을 코치가 직접 제공해 드립니다. 맞춤 커리큘럼이 확정되면, 일정을 직접 설정하고 운동을 시작 할 수\r\n");
      out.write("							있습니다.</div></li>\r\n");
      out.write("					<li><a class=\"selected2\">운동 일지는 어떻게 작성하면 되나요?</a>\r\n");
      out.write("						<div class=\"answe2\">\r\n");
      out.write("							운동량, 자세, 식단등 자유롭게 기록하세요. <br> 운동하면서 느꼈던 점이나 궁금했던 점을 작성하셔도\r\n");
      out.write("							좋아요. 직접 찍은 사진과 영상을 함께 등록하면, 정확한 자세 코칭을 받으실 수 있습니다.\r\n");
      out.write("						</div></li>\r\n");
      out.write("					<li><a class=\"selected3\">목표 달성률은 무엇인가요?</a>\r\n");
      out.write("						<div class=\"answe3\">\r\n");
      out.write("							예정된 일정의 전체 운동 중, 진행한 운동의 비율입니다. <br> 이 때 운동 진행 여부는 운동 일지 작성을\r\n");
      out.write("							기준으로 합니다. 운동을 마치시면 꼭 일지를 작성하세요!\r\n");
      out.write("						</div></li>\r\n");
      out.write("					<li><a class=\"selected4\">운동 일정을 변경하려면 어떻게 하나요?</a>\r\n");
      out.write("						<div class=\"answe4\">\r\n");
      out.write("							마이페이지 - 내 프로그램에서 운동 일정을 변경하실 수 있습니다. <br> 변경하고자 하는 요일과 시간으로\r\n");
      out.write("							일정을 변경하세요. (단 변경한 일정은 다음날 부터 적용되며, 당일 적용은 불가합니다.)\r\n");
      out.write("						</div></li>\r\n");
      out.write("					<li><a class=\"selected5\">저에게 맞는 운동 프로그램을 추천해 주실 수 있나요?</a>\r\n");
      out.write("						<div class=\"answe5\">투핏의 운동 매니저가 간단한 설문 후 커리큘럼을 추천해 드리겠습</div></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/common/gide.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/common/gide.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/common/gide.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
