/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-06-18 16:54:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/KimSoYoung/tofit/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/tofit/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1683813509779L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/index.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/footer.css\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.6.3.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/index.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	(function() {\r\n");
      out.write("		var w = window;\r\n");
      out.write("		if (w.ChannelIO) {\r\n");
      out.write("			return w.console.error(\"ChannelIO script included twice.\")\r\n");
      out.write("		}\r\n");
      out.write("		var ch = function() {\r\n");
      out.write("			ch.c(arguments)\r\n");
      out.write("		};\r\n");
      out.write("		ch.q = [];\r\n");
      out.write("		ch.c = function(args) {\r\n");
      out.write("			ch.q.push(args)\r\n");
      out.write("		};\r\n");
      out.write("		w.ChannelIO = ch;\r\n");
      out.write("		function l() {\r\n");
      out.write("			if (w.ChannelIOInitialized) {\r\n");
      out.write("				return\r\n");
      out.write("			}\r\n");
      out.write("			w.ChannelIOInitialized = true;\r\n");
      out.write("			var s = document.createElement(\"script\");\r\n");
      out.write("			s.type = \"text/javascript\";\r\n");
      out.write("			s.async = true;\r\n");
      out.write("			s.src = \"https://cdn.channel.io/plugin/ch-plugin-web.js\";\r\n");
      out.write("			var x = document.getElementsByTagName(\"script\")[0];\r\n");
      out.write("			if (x.parentNode) {\r\n");
      out.write("				x.parentNode.insertBefore(s, x)\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		if (document.readyState === \"complete\") {\r\n");
      out.write("			l()\r\n");
      out.write("		} else {\r\n");
      out.write("			w.addEventListener(\"DOMContentLoaded\", l);\r\n");
      out.write("			w.addEventListener(\"load\", l)\r\n");
      out.write("		}\r\n");
      out.write("	})();\r\n");
      out.write("	ChannelIO('boot', {\r\n");
      out.write("		\"pluginKey\" : \"4719cc3a-a174-407b-8c4c-79697be92e42\"\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<title>TOFIT</title>\r\n");
      out.write("</head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"content\">\r\n");
      out.write("		<div id=\"main\">\r\n");
      out.write("			<div id=\"main_inner\">\r\n");
      out.write("				<div class=\"video\">\r\n");
      out.write("					<video class=\"video_in\" autoplay muted loop>\r\n");
      out.write("						<source\r\n");
      out.write("							src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/SnapInsta.io-필라테스, 요가 영상 _ Pilates, Yoga Cinematic 4K-(1080p).mp4\">\r\n");
      out.write("					</video>\r\n");
      out.write("				</div>\r\n");
      out.write("				<h1>\r\n");
      out.write("					<span class=\"big_tit1\">간편한</span> <span class=\"big_tit2\">피트니스\r\n");
      out.write("						서비스,<b> 투핏</b>\r\n");
      out.write("					</span>\r\n");
      out.write("				</h1>\r\n");
      out.write("				<P>\r\n");
      out.write("					<span class=\"small_tit1\">온라인 <b>PT 예약,</b></span> <span\r\n");
      out.write("						class=\"small_tit1\"><b>투핏</b>에서 지금 시작하세요.👍🏻</span>\r\n");
      out.write("				</P>\r\n");
      out.write("				<a class=\"cta1\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/center/centerMain.do\">PT\r\n");
      out.write("					이용권 구매</a>\r\n");
      out.write("				");

				if (session.getAttribute("isLogon") == null || session.getAttribute("isLogon") == "") {
				
      out.write("\r\n");
      out.write("				<a class=\"cta2\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/login.do\">나의 피트니스\r\n");
      out.write("					서비스</a>\r\n");
      out.write("				");

				} else {
				
      out.write("\r\n");
      out.write("				<a class=\"cta2\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reserve/reserveInfo.do\">나의\r\n");
      out.write("					피트니스 서비스</a>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"bg\">\r\n");
      out.write("			<div id=\"big_title\">\r\n");
      out.write("				<div class=\"tit_inner\">\r\n");
      out.write("					<h3>\r\n");
      out.write("						<span class=\"bigt1\">나의 PT 예약 현황을 한 눈에 확인하고 싶다면,</span> <span\r\n");
      out.write("							class=\"bigt2\"><b>투핏</b> 피트니스 서비스를 시작하세요!</span>\r\n");
      out.write("					</h3>\r\n");
      out.write("					<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/thinking.svg\" alt=\"이모지\">\r\n");
      out.write("					<p>\r\n");
      out.write("						<span class=\"t1\">'오늘이 몇 회째지?' 고민은 그만!</span> <span class=\"t2\">PT\r\n");
      out.write("							구매내역, 잔여횟수, 예약현황까지</span> <span class=\"t3\">나만의 PT예약 관리 서비스를 만나보세요</span>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"product\">\r\n");
      out.write("				<div class=\"product_inner\">\r\n");
      out.write("					<h6>피트니스 서비스의 기준, 투핏</h6>\r\n");
      out.write("					<h4>\r\n");
      out.write("						<span class=\"product_t1\">PT 등록만 하면 끝?</span> <span\r\n");
      out.write("							class=\"product_t2\">피트니스 서비스란 이런 것!</span>\r\n");
      out.write("					</h4>\r\n");
      out.write("					<p>\r\n");
      out.write("						<span class=\"product_t3\">등록된 피트니스 센터에서 PT 이용권을 구매하세요.</span> <span\r\n");
      out.write("							class=\"product_t4\">구매한 PT 이용권에 따라 나만의 PT일정을 예약하세요.</span> <span\r\n");
      out.write("							class=\"product_t5\">일정에 문제가 생겼나요? 예약된 PT일정을 취소해 보세요.</span> <span\r\n");
      out.write("							class=\"product_t6\">투핏 피트니스 서비스를 통해 PT일정을 관리하면,</span> <span\r\n");
      out.write("							class=\"product_t7\"><b>나의 PT일정을 한 눈에 확인할 수 있습니다!</b></span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<img class=\"product_pig1\"\r\n");
      out.write("						src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/1img.jpeg\" alt=\"운동\"> <img\r\n");
      out.write("						class=\"product_pig2\"\r\n");
      out.write("						src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/2im.jpeg\" alt=\"운동\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"box_content\">\r\n");
      out.write("				<div class=\"box1\">\r\n");
      out.write("					<h6>투핏 제휴 피트니스 센터</h6>\r\n");
      out.write("					<h4>\r\n");
      out.write("						<span class=\"box1_t1\">시설 좋은</span> <span class=\"box1_t2\">피트니스\r\n");
      out.write("							센터를 찾으시나요?</span>\r\n");
      out.write("					</h4>\r\n");
      out.write("					<p>\r\n");
      out.write("						<span class=\"box_t3\">투핏이 엄선한 피트니스 센터!</span> <span class=\"box_t4\">청결하고\r\n");
      out.write("							최신형 기구로 가득한</span> <span class=\"box_t5\">피트니스 센터만 모았습니다.</span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<span class=\"box_t6\">전문성을 갖출 코치 선생님과 함께라면</span> <b>누구나 목표 달성\r\n");
      out.write("						성공!</b> <img class=\"box1_pic\"\r\n");
      out.write("						src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/fitnessCenter.jpg\"\r\n");
      out.write("						alt=\"피트니스센터\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"box3\">\r\n");
      out.write("					<h6>식단 고민은 끝! 투핏쇼핑몰</h6>\r\n");
      out.write("					<h4>\r\n");
      out.write("						<span class=\"box3_t1\">전용 쇼핑몰이</span> <span class=\"box3_t1\">마침내\r\n");
      out.write("							등장</span>\r\n");
      out.write("					</h4>\r\n");
      out.write("					<p>\r\n");
      out.write("						<span class=\"box3_t2\"><b>운동과 식단</b>까지 </span> <span\r\n");
      out.write("							class=\"box3_t3\">한번에 조절 가능하게</span> <span class=\"box3_t4\">만들어진\r\n");
      out.write("							쇼핑몰</span> <span class=\"box3_t5\">바로 투핏쇼핑몰입니다.</span> <span\r\n");
      out.write("							class=\"box3_t6\">투핏쇼핑몰을 이용해</span> <span>운동뿐만 아닌 식단까지</span> <span>관리해보세요.</span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<img class=\"box3_pig\"\r\n");
      out.write("						src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/shop.jpg\" alt=\"음식\"> <img\r\n");
      out.write("						class=\"box3_pig2\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/shop2.jpg\"\r\n");
      out.write("						alt=\"음식\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"box2\">\r\n");
      out.write("					<h6>꿀팁 가득 소통게시판</h6>\r\n");
      out.write("					<h4>\r\n");
      out.write("						<span class=\"box2_t1\">투핏에서</span> <span class=\"box2_t2\">얻을\r\n");
      out.write("							수 있는</span> <span class=\"box2_t3\">다양한 운동 꿀팁!</span>\r\n");
      out.write("					</h4>\r\n");
      out.write("					<p>\r\n");
      out.write("						<span class=\"box2_t4\">운동하면서 생기는</span> <span class=\"box2_t4\">다양한\r\n");
      out.write("							궁금증을 <b>소통게시판</b>에서 해결해 보세요!\r\n");
      out.write("						</span> <span class=\"box2_t4\">전문성을 갖춘 코치 선생님과도</span> <span\r\n");
      out.write("							class=\"box2_t4\">자유롭게 소통할 수 있습니다!</span>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<img class=\"box2_pig1\"\r\n");
      out.write("					src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/discuss.png\" alt=\"소통\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"content_program\">\r\n");
      out.write("				<div class=\"program_inner\">\r\n");
      out.write("					<h3>\r\n");
      out.write("						<span class=\"program_t1\">당신에게 FIT한</span> <span class=\"program_t1\">투핏\r\n");
      out.write("							서비스는?</span>\r\n");
      out.write("					</h3>\r\n");
      out.write("					<p>\r\n");
      out.write("						건강한 몸 만들기, <br> 지금 투핏에서 시작하세요.\r\n");
      out.write("					</p>\r\n");
      out.write("					<div class=\"program_content\">\r\n");
      out.write("						<div class=\"program_box1\">\r\n");
      out.write("							<h4>\r\n");
      out.write("								<span>투핏</span> <span><b>피트니스 서비스</b></span> <small>간편한\r\n");
      out.write("									PT 관리</small>\r\n");
      out.write("							</h4>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li>온라인으로 PT 이용권 구매</li>\r\n");
      out.write("								<li>나의 일정에 맞춰 PT일정 예약 및 취소</li>\r\n");
      out.write("								<li>한 눈에 확인하는 나의 PT일정</li>\r\n");
      out.write("								<li>복잡한 절차 없이 PT 이용권 환불</li>\r\n");
      out.write("								<li>전문성을 갖춘 코치 선생님과 PT</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							");

							if (session.getAttribute("isLogon") == null || session.getAttribute("isLogon") == "") {
							
      out.write("\r\n");
      out.write("							<a class=\"program_btn1\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/login.do\">나의\r\n");
      out.write("								피트니스 서비스</a>\r\n");
      out.write("							");

							} else {
							
      out.write("\r\n");
      out.write("							<a class=\"program_btn1\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reserve/reserveInfo.do\">나의\r\n");
      out.write("								피트니스 서비스</a>\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("							<img class=\"program_pig1\"\r\n");
      out.write("								src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/mypageCalendar.png\" alt=\"마이페이지\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"program_box2\">\r\n");
      out.write("							<h4>\r\n");
      out.write("								<span>투핏</span> <span><b>쇼핑몰</b></span> <small>간편한 헬스식품 구매</small>\r\n");
      out.write("							</h4>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li>다양한 헬스식품</li>\r\n");
      out.write("								<li>부족한 영양소를 채움</li>\r\n");
      out.write("								<li>맛과 건강을 함께</li>\r\n");
      out.write("								<li>투핏이 선정한 질리지 않는 헬스식품</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							<a class=\"program_btn2\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/shop/listProduct.do\">투핏쇼핑몰로 이동</a> <img\r\n");
      out.write("								class=\"program_pig2\"\r\n");
      out.write("								src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/shop2.jpg\" alt=\"헬스식품\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"last_banner\">\r\n");
      out.write("				<div class=\"last_inner\">\r\n");
      out.write("					<h3>\r\n");
      out.write("						<span>지금 바로 시작하세요!</span>\r\n");
      out.write("					</h3>\r\n");
      out.write("					<img class=\"last\"\r\n");
      out.write("						src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/emoji_cool_b.svg\" alt=\"이모티콘\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/common/index.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/common/index.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/common/index.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\r');
          out.write('\n');
          out.write('	');
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/common/index.jsp(57,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg=='removeUser'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		<script>\r\n");
          out.write("			window.onload = function() {\r\n");
          out.write("				alert(\"회원탈퇴 되었습니다. 감사합니다.\");\r\n");
          out.write("			}\r\n");
          out.write("		</script>\r\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }
}
